server:
  servlet:
    contextPath: /ark-auth-service
  port: 8080


spring:
  application:
    name: arkauth
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      schema: public
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      jdbc:
        time_zone: UTC
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  expiration:
    accessToken: 6000
    refreshToken: 86400
  private:
    key: /test/security/app.key
  public:
    key: /test/security/app.pub
