spring:
  application:
    name: auth-ms
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      schema: ${DATASOURCE_SCHEME}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT:6000}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      jdbc:
        time_zone: UTC
    hibernate:
      ddl-auto: update
server:
  servlet:
    contextPath: /auth-ms
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health
jwt:
  expiration:
    accessToken: ${JWT_EXPIRATION_ACESSTOKEN:6000}
    refreshToken: ${JWT_EXPIRATION_REFRESHTOKEN:86400}
  private:
    key: ${JWT_PRIVATE_KEY}
  public:
    key: ${JWT_PUBLIC_KEY}
